version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGP_INITDB_ROOT_USERNAME: root
      MONGP_INITDB_ROOT_PASSWORD: 12345

  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node